[package]
name = "getcraft"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true
repository.workspace = true

[dependencies]
eframe = "0.36"
egui = "0.36"
egui_extras = { version = "0.36", features = ["image", "http"] }
env_logger = "0.11.11"
getcraft-core = { version = "0.1.0", path = "../../crates/getcraft-core" }
image = { version = "0.25.10", default-features = false, features = ["png"] }
log = "0.4.34"
notify-rust = "4.18.2"
open = "5.4.4"
